import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <aside className="bg-red-500 max-w-md">aside stuff</aside>
          <div className="p-6 max-w-4xl mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
