import AppSideBar from "@/components/layout/AppSideBar";
import { authOptions } from "@/lib/auth";
import DBConnect from "@/lib/dbConnect";
import { Page } from "@/models/Page";
import { faBars, faLink } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Lato } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Toaster } from "react-hot-toast";
import "../globals.css";
import profilePic from "/default-profile-pic.jpg";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log("TEMPLATE :: session ==>>", session);
  if (!session) {
    console.log("TEMPLATE :: Redirected");
    return redirect("/");
  }

  await DBConnect();
  const page = await Page.findOne({ owner: session.user?.email! });
  console.log(
    "TEMPLATE :: session.user?.email ==>>",
    session.user?.email,
    "\n",
    "page ==>>",
    page
  );

  return (
    <html lang="en">
      <body className={lato.className}>
        <Toaster />
        <main className="md:flex min-h-screen">
          <label
            htmlFor="navCb"
            className="md:hidden ml-8 mt-4 p-4 rounded-md bg-white shadow inline-flex items-center gap-4 cursor-pointer"
          >
            <FontAwesomeIcon icon={faBars} className="w-6 h-6" />
            <span>Open Navigation</span>
          </label>
          <input type="checkbox" id="navCb" className="hidden" />
          <label
            htmlFor="navCb"
            className="backdrop hidden fixed inset-0 bg-black/70 z-10"
          />
          <aside className="bg-white w-48 p-4 pt-6 shadow fixed md:static -left-48 top-0 bottom-0 z-20 transition-all">
            <div className="sticky top-0 pt-2">
              <div className="rounded-full overflow-hidden w-24 aspect-square mx-auto relative">
                <Image
                  src={session?.user?.image || profilePic}
                  alt="avatar"
                  fill
                />
              </div>
              {page && (
                <Link
                  target="_blank"
                  href={"/" + page.uri}
                  className="text-center mt-4 flex gap-1 items-center justify-center"
                >
                  <FontAwesomeIcon
                    size="lg"
                    icon={faLink}
                    className="text-blue-500 w-6 h-6"
                  />
                  <span className="text-2xl text-gray-300">/</span>
                  <span>{page.uri}</span>
                </Link>
              )}
              <div className="text-center">
                <AppSideBar />
              </div>
            </div>
          </aside>
          <div className="grow">{children}</div>
        </main>
      </body>
    </html>
  );
}
